arreglo tests, mejoro output de pasos intermedios

diff --git a/tests/test b/tests/test
--- a/tests/test
+++ b/tests/test
@@ -65,6 +65,8 @@ function print_case(){
     if [ "$#" -ne 1 ] && [ -f "$correct" ]; then
         echo -e "${PURPLE}Expected Output:${NC}"
         cat "$correct"
+        echo -e "${PURPLE}Diff <expected >actual:${NC}"
+        diff "$correct" <(gen_output "$source")
     fi
     echo
 }
@@ -73,7 +75,7 @@ function add_case(){
     source=${1%.*}.tig
     if [ -f "$source" ]; then
         echo "Running case "${source#$DIR/}"... "
-        print_case "$source"
+        print_case "$source" show_expected_output
         read -p "Add this output? (y/n) " -n 1 -r
         echo
         if [[ $REPLY =~ ^[YysS]$ ]]
@@ -134,6 +136,29 @@ function run_case(){
     fi
 }
 
+function fix_case(){
+    source=${1%.*}.tig
+    if [ -f "$source" ]; then
+        correct=${source%.*}.out
+        printf "Testing case "${source#$DIR/}"... "
+        if [ -f "$correct" ]; then
+            gen_output "$source" | diff - "$correct" > /dev/null
+            if [ $? -eq 0 ]; then
+                OK
+                return 0
+            else
+                BAD
+                add_case "$source"
+                #~ print_case "$source" show_expected_output
+                return 1
+            fi
+        fi
+    else
+        echo -e "${RED}File $source not found.${NC}"
+        return 2
+    fi
+}
+
 
 verb="$1"
 shift
@@ -161,6 +186,23 @@ case "$verb" in
             done
         fi
         echo -e "Tests passed ${PURPLE}${passed}/${tot}${NC}"
+        ;;
+    fix)
+        compile_tiger
+        if [ "$#" -eq 0 ] || [ "$1" = "all" ]; then
+            for tfile in $(find "$DIR" -name "*.tig" | sort); do
+                correct=${tfile%.*}.out
+                if [ -f "$correct" ]; then
+                    fix_case "$tfile"
+                fi
+            done
+        else
+            while [ $# -ne 0 ]
+              do
+                fix_case "$1"
+                shift
+            done
+        fi
         ;;
      
     add)
